### PR TITLE
feat: auto complete suggestions on search bar

### PR DESCRIPTION
**Pull request by rutajdash**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

### Linked Issues

Fixes

### Description

Please describe your pull request.

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Comment by rutajdash** [comment]
@120EE0692 ensure this all works and then approve the PR.

**Comment by 120EE0692** [comment]
> @120EE0692 ensure this all works and then approve the PR.

@rutajdash to make this work in production first we need to deploy backend.

**Comment by 120EE0692** [comment]
@rutajdash before merging this make sure the this [PR](https://github.com/Monday-Morning/project-tahiti/pull/325) is merged.

**Comment by rutajdash** [comment]
@120EE0692 is this ready for merge?

**Comment by 120EE0692** [comment]
> @120EE0692 is this ready for merge?

After merging this [PR](https://github.com/Monday-Morning/project-tahiti/pull/317#issuecomment-1345370685) for sure.

**Comment by rutajdash** [comment]
@120EE0692 final review and approval please.

**Review by 120EE0692 — APPROVED** [review]

**Pull request merged**
