### PR TITLE
fix(styles): squiggle text align

### PR DESCRIPTION
**Pull request by 120EE0692**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

Fixes
squiggle text-align issue fix for the mobile screen. 
image
image

❤️Thank you!

### Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Comment by rutajdash** [comment]
@120EE0692 check this one too, for desktop view, maybe put a max limit on squiggle width?
image

**Comment by 120EE0692** [comment]
> @120EE0692 check this one too, for desktop view, maybe put a max limit on squiggle width? image

Empty space does not looks good, something is better than nothing
image

**Comment by 120EE0692** [comment]
> @120EE0692 check this one too, for desktop view, maybe put a max limit on squiggle width? image

added
image

**Comment by rutajdash** [comment]
I was referring to the gap on both sides of the red box, not the full squiggle box.

**Comment by 120EE0692** [comment]
> I was referring to the gap on both sides of the red box, not the full squiggle box.

image

**Review by rutajdash — APPROVED** [review]

**Pull request merged**
