### PR TITLE
feat:admin panel 

### PR DESCRIPTION
**Pull request by sambit-sankalp**
### Your checklist for this pull request

🚨Please review the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start _your branch_ off _default branch_.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

### Description
the layout of admin panel is made.

❤️Thank you!

### Post merge checklist

- [x] Follow steps from the [guidelines for contributing](https://github.com/Monday-Morning/project-tahiti/blob/main/CONTRIBUTING.md) to this repository.
- [x] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

### CODE REVIEW

**Review by rutajdash — COMMENTED** [review]
@sambit-sankalp is there any way to use react-router-dom or some internal router for admin like it used to be in react (pre-next) instead of making them separate pages?

**Comment by rutajdash** [comment]
Also, we can proceed with this for now. In the meanwhile, kindly have the internal design team start working on a UI/UX for this admin panel.

**Comment by sambit-sankalp** [comment]
> @sambit-sankalp is there any way to use react-router-dom or some internal router for admin like it used to be in react (pre-next) instead of making them separate pages?

In nextJs, I don't think we have such things but I am finding a way to do something in React.

**Comment by sambit-sankalp** [comment]
> Also, we can proceed with this for now. In the meanwhile, kindly have the internal design team start working on a UI/UX for this admin panel.

okay sure

**Comment by rutajdash** [comment]
> > @sambit-sankalp is there any way to use react-router-dom or some internal router for admin like it used to be in react (pre-next) instead of making them separate pages?
> 
> In nextJs, I don't think we have such things but I am finding a way to do something in React.

Do check, that way we can have the admin panel completely CSR with no requirement for SSR. Merging repo for now.

**Review by rutajdash — APPROVED** [review]

**Pull request merged**
